spring.jpa.open-in-view=true
logging.level.org.springframework.web=DEBUG
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.packagesToScan=com.eduardo.ecommerce
springdoc.swagger-ui.disable-swagger-default-url=true
logging.level.org.springdoc=DEBUG